// packages/vite-plugin-vscode/examples/vue/src/App.vue
<script lang="ts" setup>
  import {
    allComponents,
    provideVSCodeDesignSystem,
  } from "@vscode/webview-ui-toolkit";
  import { ref } from "vue";
  import { vscodeApi } from "./utils";

  provideVSCodeDesignSystem().register(allComponents);

  console.log("--inject--", window.__FLAG1__, window.__FLAG2__);

  const message = ref("");
  const state = ref("");

  function onSetState() {
    vscodeApi.setState(state.value);
  }

  function onGetState() {
    state.value = vscodeApi.getState() || "";
  }

  function onPostMessage() {
    vscodeApi.postMessage({
      data: `💬: ${message.value || "Empty"}`,
      type: "hello",
    });

    setTimeout(() => {
      vscodeApi.post("hello3", `⛅: ${message.value || "Empty"}`);
    }, 100);
  }

  const receive = ref("");
  function onPostAndReceive() {
    vscodeApi
      .postAndReceive("hello2", `😀: ${message.value || "Empty"}`)
      .then((data: any) => {
        console.log("data", data);
        receive.value = data;
      });
  }

  vscodeApi.on("hello3", (data: any) => {
    console.log("watch [hello3]: ", data);
  });
</script>

<template>
  <main>
    <h1>Hello Vue!!!!!</h1>
    <vscode-button @click="onPostMessage"> Post Message </vscode-button>
    <div style="margin-top: 8px">
      <vscode-button @click="onPostAndReceive">
        Post Message And Receive
      </vscode-button>
      <span style="margin-left: 8px" v-if="receive">{{ receive }}</span>
    </div>
    <div>
      <vscode-text-field
        :value="message"
        @input="e => (message = e.target.value)"
      >
        Please enter a message
      </vscode-text-field>
      <div>Message is: {{ message }}</div>
    </div>
    <div>
      <vscode-text-field :value="state" @input="e => (state = e.target.value)">
        Please enter a state
      </vscode-text-field>
      <div>State is: {{ state }}</div>
      <div>
        <vscode-button @click="onSetState"> setState </vscode-button>
        <vscode-button style="margin-left: 8px" @click="onGetState">
          getState
        </vscode-button>
      </div>
    </div>
  </main>
</template>

<style>
  main {
    display: flex;
    flex-direction: column;
    align-items: flex-start;
    justify-content: center;
    height: 100%;
  }
</style>

// packages/vite-plugin-vscode/examples/react/src/App.tsx
import {
  VSCodeButton,
  VSCodeTextField,
} from "@vscode/webview-ui-toolkit/react";
import { useCallback, useState } from "react";
import { vscode } from "./utils/vscode";

import "./App.css";

function App() {
  const [message, setMessage] = useState("");
  const [state, setState] = useState("");

  const onSetState = useCallback(() => {
    vscode.setState(state);
  }, [state]);
  const onGetState = useCallback(() => {
    setState((vscode.getState() || "") as string);
  }, []);

  const onPostMessage = useCallback(() => {
    vscode.postMessage({
      data: `💬: ${message || "Empty"}`,
      type: "hello",
    });
  }, [message]);

  const onMessageInput = useCallback((e: Event) => {
    const target = e.target as HTMLInputElement | null;
    setMessage(target?.value ?? "");
  }, []);
  const onStateInput = useCallback((e: Event) => {
    const target = e.target as HTMLInputElement | null;
    setState(target?.value ?? "");
  }, []);

  return (
    <main>
      <h1>Hello React!</h1>
      <VSCodeButton onClick={onPostMessage}>Test VSCode Message</VSCodeButton>
      <div>
        <VSCodeTextField onInput={onMessageInput} value={message}>
          Please enter a message
        </VSCodeTextField>
        <div>
          Message is:
          {message}
        </div>
      </div>
      <div>
        <VSCodeTextField onInput={onStateInput} value={state}>
          Please enter a state
        </VSCodeTextField>
        <div>
          State is:
          {state}
        </div>
        <div>
          <VSCodeButton onClick={onSetState}>setState</VSCodeButton>
          <VSCodeButton onClick={onGetState} style={{ marginLeft: "8px" }}>
            getState
          </VSCodeButton>
        </div>
      </div>
    </main>
  );
}

export default App;
